### ISSUE TITLE
Pupcloud stopped without warning (I think) ...

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#48]
This is not the best of reports, I know.

Had Pupcloud running in Docker. Seemed to have stopped running/responding but I am not such a Docker expert to know where the fault lies.

Log extract in case it is a "Pupcloud" issue.

```
/pupcloud$ docker-compose logs pupcloud
Attaching to pupcloud
pupcloud    | Pupcloud v0.8.0 (c) 2022 Germano Rizzo
pupcloud    |  - Serving dir /data
pupcloud    |    + Read/Write
pupcloud    |    + With password
pupcloud    |    + With max upload size: 32 MiB
pupcloud    |    + Will NOT follow symbolic links
pupcloud    |  - Server running on port 17178
pupcloud    | panic: runtime error: invalid memory address or nil pointer dereference
pupcloud    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6ee065]
pupcloud    | 
pupcloud    | goroutine 2446 [running]:
pupcloud    | github.com/proofrock/pupcloud/files.LsFile({0xc00030aa20, 0x5c}, 0x0)
pupcloud    |   /app/pupcloud/src/files/files.go:67 +0xa5
pupcloud    | github.com/proofrock/pupcloud/files.LsDir({0xc0000603c0?, 0x34?}, 0x0)
pupcloud    |   /app/pupcloud/src/files/files.go:120 +0x23c
pupcloud    | main.ls(0xc0001fd080)
pupcloud    |   /app/pupcloud/src/handlers.go:73 +0x185
pupcloud    | github.com/gofiber/fiber/v2.(*App).next(0xc000144000, 0xc0001fd080)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:132 +0x1be
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0x2000000?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:802 +0x53
pupcloud    | main.launchMainApp.func1(0xc00008c0f0?)
pupcloud    |   /app/pupcloud/src/main.go:301 +0x335
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0x86fdc0?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/filesystem.New.func1(0xc0001fd080)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/filesystem/filesystem.go:145 +0x369
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0001fd080?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/csrf.New.func1(0x100?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/csrf/csrf.go:98 +0x35b
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000151600?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/compress.New.func3(0xc0001fd080)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/compress/compress.go:54 +0x45
pupcloud    | github.com/gofiber/fiber/v2.(*App).next(0xc000144000, 0xc0001fd080)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:132 +0x1be
pupcloud    | github.com/gofiber/fiber/v2.(*App).handler(0xc000144000, 0x4a1d77?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:159 +0x45
pupcloud    | github.com/valyala/fasthttp.(*Server).serveConn(0xc0000d2480, {0x872d30?, 0xc0000a4450})
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/server.go:2338 +0x1268
pupcloud    | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000076000, 0xc000680460)
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:224 +0xa9
pupcloud    | github.com/valyala/fasthttp.(*workerPool).getCh.func1()
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:196 +0x38
pupcloud    | created by github.com/valyala/fasthttp.(*workerPool).getCh
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:195 +0x1b0
pupcloud    | Pupcloud v0.8.0 (c) 2022 Germano Rizzo
pupcloud    |  - Serving dir /data
pupcloud    |    + Read/Write
pupcloud    |    + With password
pupcloud    |    + With max upload size: 32 MiB
pupcloud    |    + Will NOT follow symbolic links
pupcloud    |  - Server running on port 17178
pupcloud    | Pupcloud v0.8.0 (c) 2022 Germano Rizzo
pupcloud    |  - Serving dir /data
pupcloud    |    + Read/Write
pupcloud    |    + With password
pupcloud    |    + With max upload size: 32 MiB
pupcloud    |    + Will NOT follow symbolic links
pupcloud    |  - Server running on port 17178
pupcloud    | Pupcloud v0.8.0 (c) 2022 Germano Rizzo
pupcloud    |  - Serving dir /data
pupcloud    |    + Read/Write
pupcloud    |    + With password
pupcloud    |    + With max upload size: 32 MiB
pupcloud    |    + Will NOT follow symbolic links
pupcloud    |  - Server running on port 17178
pupcloud    | panic: runtime error: invalid memory address or nil pointer dereference
pupcloud    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6ee065]
pupcloud    | 
pupcloud    | goroutine 2488 [running]:
pupcloud    | github.com/proofrock/pupcloud/files.LsFile({0xc000014960, 0x46}, 0x0)
pupcloud    |   /app/pupcloud/src/files/files.go:67 +0xa5
pupcloud    | main.file(0xc000095b80)
pupcloud    |   /app/pupcloud/src/handlers.go:103 +0x1aa
pupcloud    | github.com/gofiber/fiber/v2.(*App).next(0xc0000001e0, 0xc000095b80)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:132 +0x1be
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0x2000000?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:802 +0x53
pupcloud    | main.launchMainApp.func1(0xc00001a130?)
pupcloud    |   /app/pupcloud/src/main.go:301 +0x335
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0x86fdc0?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/filesystem.New.func1(0xc000095b80)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/filesystem/filesystem.go:145 +0x369
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000095b80?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/csrf.New.func1(0x70?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/csrf/csrf.go:98 +0x35b
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000273180?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/compress.New.func3(0xc000095b80)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/compress/compress.go:54 +0x45
pupcloud    | github.com/gofiber/fiber/v2.(*App).next(0xc0000001e0, 0xc000095b80)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:132 +0x1be
pupcloud    | github.com/gofiber/fiber/v2.(*App).handler(0xc0000001e0, 0x4a1d77?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:159 +0x45
pupcloud    | github.com/valyala/fasthttp.(*Server).serveConn(0xc00008e480, {0x872d30?, 0xc0001022d0})
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/server.go:2338 +0x1268
pupcloud    | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000775e0, 0xc000110160)
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:224 +0xa9
pupcloud    | github.com/valyala/fasthttp.(*workerPool).getCh.func1()
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:196 +0x38
pupcloud    | created by github.com/valyala/fasthttp.(*workerPool).getCh
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:195 +0x1b0
pupcloud    | panic: runtime error: invalid memory address or nil pointer dereference
pupcloud    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6ee065]
pupcloud    | 
pupcloud    | goroutine 2522 [running]:
pupcloud    | github.com/proofrock/pupcloud/files.LsFile({0xc0002a6b90, 0x46}, 0x0)
pupcloud    |   /app/pupcloud/src/files/files.go:67 +0xa5
pupcloud    | main.file(0xc00041a2c0)
pupcloud    |   /app/pupcloud/src/handlers.go:103 +0x1aa
pupcloud    | github.com/gofiber/fiber/v2.(*App).next(0xc0000001e0, 0xc00041a2c0)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:132 +0x1be
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0x2000000?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:802 +0x53
pupcloud    | main.launchMainApp.func1(0xc00001a130?)
pupcloud    |   /app/pupcloud/src/main.go:301 +0x335
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0x86fdc0?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/filesystem.New.func1(0xc00041a2c0)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/filesystem/filesystem.go:145 +0x369
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00041a2c0?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/csrf.New.func1(0x70?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/csrf/csrf.go:98 +0x35b
pupcloud    | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000272c00?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/ctx.go:799 +0x43
pupcloud    | github.com/gofiber/fiber/v2/middleware/compress.New.func3(0xc00041a2c0)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/middleware/compress/compress.go:54 +0x45
pupcloud    | github.com/gofiber/fiber/v2.(*App).next(0xc0000001e0, 0xc00041a2c0)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:132 +0x1be
pupcloud    | github.com/gofiber/fiber/v2.(*App).handler(0xc0000001e0, 0x4a1d77?)
pupcloud    |   /app/pkg/mod/github.com/gofiber/fiber/v2@v2.33.0/router.go:159 +0x45
pupcloud    | github.com/valyala/fasthttp.(*Server).serveConn(0xc00008e480, {0x872d30?, 0xc00000e490})
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/server.go:2338 +0x1268
pupcloud    | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000775e0, 0xc0007b2120)
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:224 +0xa9
pupcloud    | github.com/valyala/fasthttp.(*workerPool).getCh.func1()
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:196 +0x38
pupcloud    | created by github.com/valyala/fasthttp.(*workerPool).getCh
pupcloud    |   /app/pkg/mod/github.com/valyala/fasthttp@v1.36.0/workerpool.go:195 +0x1b0
```

**Comment by proofrock** [comment]
That’s great, I have a stacktrace to work with! Thanks!

**Comment by DarrenPIngram** [comment]
Good. I guess. Does this possibly signify a software issue or a fault with my Docket or server (out of your control)?


Darren P Ingram,  via mobile device.

**Comment by proofrock** [comment]
I would say the second; but I hope to be able to catch it in a nicer way and be able to at least warn for it in a dialog or such. There’s definitely something that makes the Go filesystem routines angry. Or perhaps I don’t use them in the right way.

**Comment by DarrenPIngram** [comment]
Ok - good to know a resolution either way. I've not noticed any other problems on that server & it is lightly laden. Of course, happy to work with you to track issues.


—- 
Via iPad. Hopefully with not too many typos.

**Comment by proofrock** [comment]
In brief: I get a file descriptor, it throws an error but I only check that the error is not "file not found". Your error is not that, but I try to use the descriptor anyway, and it explodes. My mistake is that I must check and report any error; but the filesystem access is reporting an access error anyway, that I don't know. I'll make a version that reports any filesystem error, so that we can see what it is. The filesystem access is certainly failing, but why... I cannot tell yet.

**Comment by marioscube** [comment]
Is this issue related to #45 ?

What king of mount would it be? Webdav, samba, nfs, Google Drive. Dropbox. etc?

**Comment by proofrock** [comment]
Seems to me it's related, too. Maybe Darren can confirm and we can merge them?

**Comment by DarrenPIngram** [comment]
Sorry, on even more "reduced power" at the weekend. 
Yes, I think the issues are related. Certainly (in general) it would be good for better error reporting and logging.

I believe there is an issue with a non-Docker rclone and a Docker instance, even with the correct bind-mounting. Am now testing both a Docker rclone and combined application compose file using a shared network, to see if this makes any difference.

**Comment by DarrenPIngram** [comment]
> What kind of mount would it be? Webdav, samba, nfs, Google Drive. Dropbox. etc?

In my case it was rclone, mounted via systemd, to Dropbox (which was working in other instances, but not the non-Docker/Docker cross).

**Comment by marioscube** [comment]
Mounted a Dropbox with rclone (not in docker) and left it open.

After 8 hours Dropbox was still mounted. No errors in syslog.

Tomorrow I will test with pupcloud, rclone and Dropbox.

**Comment by proofrock** [comment]
@DarrenPIngram , @marioscube thanks and please test this pre-release docker image `germanorizzo/puptest:v0.8.1_b1` (notice the "puptest"). It exposes more filesystem errors. Look for a red bar at the bottom, if an error is encountered after an action of yours it shows it for a few seconds.

**Comment by DarrenPIngram** [comment]
I don't know if the level of incoming usage & overall mount size is relevant.  So many variables.

Presently looking closer at memory management, Docker-vs-no-Docker (overhead/ loading issue?) and other tweaks.

It might exonerate FB/Pupcloud (or show a bug elsewhere in rclone/fuse/OS/Docker) but it may lead to better trapping and resiliency too, so hopefully not entirely in vain.


—- 
Via iPad. Hopefully with not too many typos.

**Comment by marioscube** [comment]
I trashed pupcloud around a bit for ca 1 hour, but no errors. At least no errors that I did not cause myself. pupcloud on docker does not like broken directories.

I saw a strange problem with pupcloud/docjer that I could not reproduce with regular pupcloud. 
That is that pupcloud did not present all txt files as readable in a browser.
I even made a few new txt files with nano, not readable.
When copied to regular pupcloud, no problem.

![Screenshot 2022-05-17 at 00 52 09](https://user-images.githubusercontent.com/20281601/168695139-e6ecc771-6221-40fd-a067-059f44c0578d.png)

The only other machine with docker on it to test died on me this weekend......... :-(
And as I want to buy an Apple m2 MacBook Air, Pro or mini in the near future I do not want to spend any money on replacing the broken linux PC. Maybe  tomorrow (Tuesday/Wednesday) I can revive an old PC from the mothballs and install Docker on it.

**Comment by DarrenPIngram** [comment]
Sorry, this week has been a bit of a blur and I'm rather behind. My
long-term sickness is not helping matters too.
Not forgotten you.

**Comment by marioscube** [comment]
Life comes first for all of us!
